[app]
  name = "onlystash"

[build]
  cmd = "npm install && node bot.js"

[runtime]
  port = 8080

[[mounts]]
  destination = "/mnt/files"
  source = "files/"
  type = "local"

[network]
  [[services]]
    internal_port = 8080
    protocol = "tcp"

  [[services.ports]]
    port = 80
    protocol = "tcp"

  [[services.ports]]
    port = 443
    protocol = "tcp"
